#dist: xenial
os:
  - linux
  - windows
sudo: false
language: cpp
#compiler: gcc


matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - g++-8
      before_script: cd runtime
      script:
        - CXX=/usr/bin/g++-8 
        - CC=/usr/bin/gcc-8
        - cmake -DCMAKE_BUILD_TYPE=Release -B"cmake-build-linux" .
        - make
        - cd src
        - ls -l
    - os: windows
      env:
        - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
      before_script: cd runtime
      script:
        - export PATH=$MSBUILD_PATH:$PATH
        - cmake -B"visual-studio-project" -G"Visual Studio 15 2017 Win64" .
        - ls -l
        - MSBuild.exe altv-clr-host.sln /p:Platform=x64
        - ls -l
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: eYKVpb7Or9sI3GFJtnd1k5Hx4fRiQaFaVFZCFLICD5tx2SHukokd0b2Tse66S37FCOEl57irFyJtB3L7rWF12RUZuLsHcX+woZlvqF3NO+7fmK+Ug9sTeqOwtOHt/PTMN7D3S3sIpW4Vs5BrBJv23K2VUVKgo4bcMseuBpaPM/Qe9/aTTcWPvAHejLkmn2Cz9HJM0A74/QBZigTGi8SHHh9nTiN3ZoRoCorKzu9/ZlVScRZI+G8U7Kkfs8t2QWD+wiw7SGEIp/dUGoXW7EtqODDwntANZwpkQ+AJVbonCmNkZtr7SJLntNrC4zlIfuGLL+Wr50v77I2q1AAI+8rL3PCSe3V9dpjheztooJyst5Ir7WVqvROJ2U2tYoKvEMiL0Wo7Ffq30NJ+d4xyaovVffdUIAyqqxA+tsorvNSju55CQXTkVGnyrbRAsYK/bh4k8LIln868RqAffzGkXmquW7dGiHAVF/fREWTxJAx45acp2AcB0OkWtA3KgO6i/zSE9BP+PabxXYY7tAl1gbXcRvB08mnW43cbCqJ00Hp2G5oWcNo1EH2Gmf7Jp4NlXOcq2zOddBhUImx+kG7v9y4nCu3KvtYOeY67t8TYF2U6Az+yxxyX1jHVtSkt8iUfk3K4jl6w5X31gq4Ss5f1GKrny0rWPRptBnuYtYdPIMGLHVo=
  file: "libcsharp-module.so"
  on:
    repo: FabianTerhorst/coreclr-module
    tags: true
    branches:
      only:
        - master
