#os:
#- linux
#- windows
#filter_secrets: false
#sudo: false
#language: cpp
env:
  - GITHUB_DEPLOY_PRERELEASE=$(if echo $TRAVIS_TAG | grep -q "\-" ; then echo true; else echo false; fi) WINDOWS_BETA=$(if [ "$GITHUB_DEPLOY_PRERELEASE" = true ] && [ "$TRAVIS_OS_NAME" = "windows" ] ; then echo true; else echo false; fi) LINUX_BETA=$(if [ "$GITHUB_DEPLOY_PRERELEASE" = true ] && [ "$TRAVIS_OS_NAME" = "linux" ] ; then echo true; else echo false; fi) WINDOWS_STABLE=$(if [ "$GITHUB_DEPLOY_PRERELEASE" = false ] && [ "$TRAVIS_OS_NAME" = "windows" ] ; then echo true; else echo false; fi) LINUX_STABLE=$(if [ "$GITHUB_DEPLOY_PRERELEASE" = false ] && [ "$TRAVIS_OS_NAME" = "linux" ] ; then echo true; else echo false; fi)
#branches:
#  only:
#    - master
#    - dev
matrix:
  include:
  - os: linux
    dist: xenial
    language: cpp
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-8
        - g++-8
    script:
      - cd runtime
      - echo "$GITHUB_DEPLOY_PRERELEASE"
      - mkdir build && cd build
      - if [ "$TRAVIS_OS_NAME" = "linux" ]; then if ! [ -x "$(command /usr/bin/g++-8 -v)" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;sudo apt-get update;sudo apt-get -y install gcc-8 g++-8 ; fi ; fi
      - if [ "$TRAVIS_OS_NAME" = "linux" ]; then CXX=/usr/bin/g++-8 ; fi
      - if [ "$TRAVIS_OS_NAME" = "linux" ]; then CC=/usr/bin/gcc-8 ; fi
      - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo .. ; fi
      - if [ "$TRAVIS_OS_NAME" = "windows" ]; then cmake -G"Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=RelWithDebInfo -T host=x64 .. ; fi
      - cmake --build . --config Release
      - cd src
      - if [ "$TRAVIS_OS_NAME" = "windows" ]; then cd Release ; fi
      - echo "${TRAVIS_BUILD_NUMBER}"
  - os: windows
    filter_secrets: false
    language: cpp
    script:
      - cd runtime
      - echo "$GITHUB_DEPLOY_PRERELEASE"
      - mkdir build && cd build
      - if [ "$TRAVIS_OS_NAME" = "linux" ]; then if ! [ -x "$(command /usr/bin/g++-8 -v)" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;sudo apt-get update;sudo apt-get -y install gcc-8 g++-8 ; fi ; fi
      - if [ "$TRAVIS_OS_NAME" = "linux" ]; then CXX=/usr/bin/g++-8 ; fi
      - if [ "$TRAVIS_OS_NAME" = "linux" ]; then CC=/usr/bin/gcc-8 ; fi
      - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo .. ; fi
      - if [ "$TRAVIS_OS_NAME" = "windows" ]; then cmake -G"Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=RelWithDebInfo -T host=x64 .. ; fi
      - cmake --build . --config Release
      - cd src
      - if [ "$TRAVIS_OS_NAME" = "windows" ]; then cd Release ; fi
      - echo "${TRAVIS_BUILD_NUMBER}"
  - dist: xenial
    addons:
      snaps:
      - name: dotnet-sdk
        classic: true
        channel: latest/beta
    sudo: required
    language: csharp
    mono: none
    script:
      - sudo snap alias dotnet-sdk.dotnet dotnet
      - dotnet --version
deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: SHN0O0J2NFHAXP5bIRKufF3u8RqHDSKSNbVNXKnDS5FXJkhwDlHYfL1mF9xIlkAUSNvYvrKaReDAxWwRulKWisZi4JXA4OL96j2Pqiovw7npomDmEQpXLC8TgiH9TvkIFFXr4L5Cm6zzXTVjrI2FA1WiHR2rga1A367dCVX0wdSjsH4qwC3CsNFBhStsbPMQl49U2hHGe+Nl02LkzSqS0QBZ6RZsChF+fzs35512Xvfiz0qXExCIIQpIYbnPAKbNA4vd6/zTkj72xYYsK8pKGKu56ENCPf2uvzfacUDQKrTKLTVVVWlJ8865VfIwjPixfD/dvnD4XZ/mC3SQbAwEE5WjSApOXCs/eL/zKq4Wa3oaJTc0mFf31wCySAQfL3vD51Wu/pjPuixsH1o6JPxWZuGA5KbL7Bi0D3I8T3mD4CJoPwIYbmu/6kwUHbOi/Nd9fb0YraL9k1uX4WzROIpGLbADccr1L7itGVdnhD5vlrp07ETluOxyJZlsB4gNVaSk4MUAppNVlXAi/4UOmEmQYIZRg1akO+4nDN0+nfwzNRSM4chSDBFwDBthqsADErFf5yFGy9JmLHLD2qkeSjqEm/rc1a2zV66nucVmwKHZyPL92GhGkguxsYKFNu/42382W1wHJ47nDCpEQWOVgFgix7xdgSKeZiYvoEs0JgWSjLU=
    file: libcsharp-module.so
    on:
      repo: FabianTerhorst/coreclr-module
      condition: "$LINUX_STABLE = true"
      tags: true
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: SHN0O0J2NFHAXP5bIRKufF3u8RqHDSKSNbVNXKnDS5FXJkhwDlHYfL1mF9xIlkAUSNvYvrKaReDAxWwRulKWisZi4JXA4OL96j2Pqiovw7npomDmEQpXLC8TgiH9TvkIFFXr4L5Cm6zzXTVjrI2FA1WiHR2rga1A367dCVX0wdSjsH4qwC3CsNFBhStsbPMQl49U2hHGe+Nl02LkzSqS0QBZ6RZsChF+fzs35512Xvfiz0qXExCIIQpIYbnPAKbNA4vd6/zTkj72xYYsK8pKGKu56ENCPf2uvzfacUDQKrTKLTVVVWlJ8865VfIwjPixfD/dvnD4XZ/mC3SQbAwEE5WjSApOXCs/eL/zKq4Wa3oaJTc0mFf31wCySAQfL3vD51Wu/pjPuixsH1o6JPxWZuGA5KbL7Bi0D3I8T3mD4CJoPwIYbmu/6kwUHbOi/Nd9fb0YraL9k1uX4WzROIpGLbADccr1L7itGVdnhD5vlrp07ETluOxyJZlsB4gNVaSk4MUAppNVlXAi/4UOmEmQYIZRg1akO+4nDN0+nfwzNRSM4chSDBFwDBthqsADErFf5yFGy9JmLHLD2qkeSjqEm/rc1a2zV66nucVmwKHZyPL92GhGkguxsYKFNu/42382W1wHJ47nDCpEQWOVgFgix7xdgSKeZiYvoEs0JgWSjLU=
    file: csharp-module.dll
    on:
      repo: FabianTerhorst/coreclr-module
      condition: "$WINDOWS_STABLE = true"
      tags: true
  - provider: releases
    skip_cleanup: true
    prerelease: true
    api_key:
      secure: SHN0O0J2NFHAXP5bIRKufF3u8RqHDSKSNbVNXKnDS5FXJkhwDlHYfL1mF9xIlkAUSNvYvrKaReDAxWwRulKWisZi4JXA4OL96j2Pqiovw7npomDmEQpXLC8TgiH9TvkIFFXr4L5Cm6zzXTVjrI2FA1WiHR2rga1A367dCVX0wdSjsH4qwC3CsNFBhStsbPMQl49U2hHGe+Nl02LkzSqS0QBZ6RZsChF+fzs35512Xvfiz0qXExCIIQpIYbnPAKbNA4vd6/zTkj72xYYsK8pKGKu56ENCPf2uvzfacUDQKrTKLTVVVWlJ8865VfIwjPixfD/dvnD4XZ/mC3SQbAwEE5WjSApOXCs/eL/zKq4Wa3oaJTc0mFf31wCySAQfL3vD51Wu/pjPuixsH1o6JPxWZuGA5KbL7Bi0D3I8T3mD4CJoPwIYbmu/6kwUHbOi/Nd9fb0YraL9k1uX4WzROIpGLbADccr1L7itGVdnhD5vlrp07ETluOxyJZlsB4gNVaSk4MUAppNVlXAi/4UOmEmQYIZRg1akO+4nDN0+nfwzNRSM4chSDBFwDBthqsADErFf5yFGy9JmLHLD2qkeSjqEm/rc1a2zV66nucVmwKHZyPL92GhGkguxsYKFNu/42382W1wHJ47nDCpEQWOVgFgix7xdgSKeZiYvoEs0JgWSjLU=
    file: libcsharp-module.so
    on:
      repo: FabianTerhorst/coreclr-module
      condition: "$LINUX_BETA = true"
      tags: true
  - provider: releases
    skip_cleanup: true
    prerelease: true
    api_key:
      secure: SHN0O0J2NFHAXP5bIRKufF3u8RqHDSKSNbVNXKnDS5FXJkhwDlHYfL1mF9xIlkAUSNvYvrKaReDAxWwRulKWisZi4JXA4OL96j2Pqiovw7npomDmEQpXLC8TgiH9TvkIFFXr4L5Cm6zzXTVjrI2FA1WiHR2rga1A367dCVX0wdSjsH4qwC3CsNFBhStsbPMQl49U2hHGe+Nl02LkzSqS0QBZ6RZsChF+fzs35512Xvfiz0qXExCIIQpIYbnPAKbNA4vd6/zTkj72xYYsK8pKGKu56ENCPf2uvzfacUDQKrTKLTVVVWlJ8865VfIwjPixfD/dvnD4XZ/mC3SQbAwEE5WjSApOXCs/eL/zKq4Wa3oaJTc0mFf31wCySAQfL3vD51Wu/pjPuixsH1o6JPxWZuGA5KbL7Bi0D3I8T3mD4CJoPwIYbmu/6kwUHbOi/Nd9fb0YraL9k1uX4WzROIpGLbADccr1L7itGVdnhD5vlrp07ETluOxyJZlsB4gNVaSk4MUAppNVlXAi/4UOmEmQYIZRg1akO+4nDN0+nfwzNRSM4chSDBFwDBthqsADErFf5yFGy9JmLHLD2qkeSjqEm/rc1a2zV66nucVmwKHZyPL92GhGkguxsYKFNu/42382W1wHJ47nDCpEQWOVgFgix7xdgSKeZiYvoEs0JgWSjLU=
    file: csharp-module.dll
    on:
      repo: FabianTerhorst/coreclr-module
      condition: "$WINDOWS_BETA = true"
      tags: true
  - provider: script
    skip_cleanup: true
    script: cd .. && cd .. && cd .. && cd .. && mkdir upload && move .\runtime\build\src\Release\csharp-module.dll .\upload && cdn-win.exe .\upload coreclr-module/stable/x64_win32 "${TRAVIS_BUILD_NUMBER}"
    on:
      repo: FabianTerhorst/coreclr-module
      condition: "$WINDOWS_STABLE = true"
      tags: true
  - provider: script
    skip_cleanup: true
    script: cd .. && cd .. && cd .. && chmod +x ./cdn-linux && mkdir upload && mv ./runtime/build/src/libcsharp-module.so ./upload/libcsharp-module.so && ./cdn-linux ./upload coreclr-module/stable/x64_linux "${TRAVIS_BUILD_NUMBER}"
    on:
      repo: FabianTerhorst/coreclr-module
      condition: "$LINUX_STABLE = true"
      tags: true
  - provider: script
    skip_cleanup: true
    prerelease: true
    script: cd .. && cd .. && cd .. && cd .. && mkdir upload && move .\runtime\build\src\Release\csharp-module.dll .\upload && cdn-win.exe .\upload coreclr-module/beta/x64_win32 "${TRAVIS_BUILD_NUMBER}"
    on:
      repo: FabianTerhorst/coreclr-module
      condition: "$WINDOWS_BETA = true"
      tags: true
  - provider: script
    skip_cleanup: true
    prerelease: true
    script: cd .. && cd .. && cd .. && chmod +x ./cdn-linux && mkdir upload && mv ./runtime/build/src/libcsharp-module.so ./upload/libcsharp-module.so && ./cdn-linux ./upload coreclr-module/beta/x64_linux "${TRAVIS_BUILD_NUMBER}"
    on:
      repo: FabianTerhorst/coreclr-module
      condition: "$LINUX_BETA = true"
      tags: true
