os:
- linux
- windows
filter_secrets: false
sudo: false
language: cpp
matrix:
  include:
  - os: linux
    dist: xenial
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-8
        - g++-8
        - clang
  - os: windows
  - filter_secrets: false
before_script: cd runtime
script:
- mkdir build && cd build
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then apt-get update && apt-get install -y \
  xz-utils \
  build-essential \
  gcc-8 \
  g++-8 \
  curl \
  ninja-build \
  git \
  python2.7 \
  && ln -s /usr/bin/python2.7 /usr/bin/python \
  && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 700 --slave /usr/bin/g++ g++ /usr/bin/g++-7 \
  && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 800 --slave /usr/bin/g++ g++ /usr/bin/g++-8 \
  && rm -rf /var/lib/apt/lists/* \
  && curl -SL http://releases.llvm.org/7.0.1/clang+llvm-7.0.1-x86_64-linux-gnu-ubuntu-18.04.tar.xz | tar -xJC . \
  && cp -R clang+llvm-7.0.1-x86_64-linux-gnu-ubuntu-18.04/* /usr/local/ \
  && curl -SL https://nodejs.org/dist/v10.15.0/node-v10.15.0-linux-x64.tar.xz | tar -xJC . \
  && cp -R node-v10.15.0-linux-x64/* /usr/local/ \
  && curl -SL https://github.com/Kitware/CMake/releases/download/v3.13.3/cmake-3.13.3-Linux-x86_64.tar.gz | tar xvz -C . \
  && rm -rf /usr/local/man \
  && cp -rf cmake-3.13.3-Linux-x86_64/* /usr/local/ ; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then if ! [ -x "$(command /usr/bin/g++-8 -v)" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;sudo apt-get update;sudo apt-get -y install gcc-8 g++-8 ; fi ; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then CXX=/usr/bin/g++-8 ; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then CC=/usr/bin/gcc-8 ; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo .. ; fi
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then cmake -G"Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=RelWithDebInfo -T host=x64 .. ; fi
- cmake --build . --config Release
- cd src
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then cd Release ; fi
deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: SHN0O0J2NFHAXP5bIRKufF3u8RqHDSKSNbVNXKnDS5FXJkhwDlHYfL1mF9xIlkAUSNvYvrKaReDAxWwRulKWisZi4JXA4OL96j2Pqiovw7npomDmEQpXLC8TgiH9TvkIFFXr4L5Cm6zzXTVjrI2FA1WiHR2rga1A367dCVX0wdSjsH4qwC3CsNFBhStsbPMQl49U2hHGe+Nl02LkzSqS0QBZ6RZsChF+fzs35512Xvfiz0qXExCIIQpIYbnPAKbNA4vd6/zTkj72xYYsK8pKGKu56ENCPf2uvzfacUDQKrTKLTVVVWlJ8865VfIwjPixfD/dvnD4XZ/mC3SQbAwEE5WjSApOXCs/eL/zKq4Wa3oaJTc0mFf31wCySAQfL3vD51Wu/pjPuixsH1o6JPxWZuGA5KbL7Bi0D3I8T3mD4CJoPwIYbmu/6kwUHbOi/Nd9fb0YraL9k1uX4WzROIpGLbADccr1L7itGVdnhD5vlrp07ETluOxyJZlsB4gNVaSk4MUAppNVlXAi/4UOmEmQYIZRg1akO+4nDN0+nfwzNRSM4chSDBFwDBthqsADErFf5yFGy9JmLHLD2qkeSjqEm/rc1a2zV66nucVmwKHZyPL92GhGkguxsYKFNu/42382W1wHJ47nDCpEQWOVgFgix7xdgSKeZiYvoEs0JgWSjLU=
    file: libcsharp-module.so
    on:
      repo: FabianTerhorst/coreclr-module
      condition: "$TRAVIS_OS_NAME = linux"
      tags: true
      branches:
        only:
        - master
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: SHN0O0J2NFHAXP5bIRKufF3u8RqHDSKSNbVNXKnDS5FXJkhwDlHYfL1mF9xIlkAUSNvYvrKaReDAxWwRulKWisZi4JXA4OL96j2Pqiovw7npomDmEQpXLC8TgiH9TvkIFFXr4L5Cm6zzXTVjrI2FA1WiHR2rga1A367dCVX0wdSjsH4qwC3CsNFBhStsbPMQl49U2hHGe+Nl02LkzSqS0QBZ6RZsChF+fzs35512Xvfiz0qXExCIIQpIYbnPAKbNA4vd6/zTkj72xYYsK8pKGKu56ENCPf2uvzfacUDQKrTKLTVVVWlJ8865VfIwjPixfD/dvnD4XZ/mC3SQbAwEE5WjSApOXCs/eL/zKq4Wa3oaJTc0mFf31wCySAQfL3vD51Wu/pjPuixsH1o6JPxWZuGA5KbL7Bi0D3I8T3mD4CJoPwIYbmu/6kwUHbOi/Nd9fb0YraL9k1uX4WzROIpGLbADccr1L7itGVdnhD5vlrp07ETluOxyJZlsB4gNVaSk4MUAppNVlXAi/4UOmEmQYIZRg1akO+4nDN0+nfwzNRSM4chSDBFwDBthqsADErFf5yFGy9JmLHLD2qkeSjqEm/rc1a2zV66nucVmwKHZyPL92GhGkguxsYKFNu/42382W1wHJ47nDCpEQWOVgFgix7xdgSKeZiYvoEs0JgWSjLU=
    file: csharp-module.dll
    on:
      repo: FabianTerhorst/coreclr-module
      condition: "$TRAVIS_OS_NAME = windows"
      tags: true
      branches:
        only:
        - master
  - provider: script
    skip_cleanup: true
    script: cd .. && cd .. && cd .. && cd .. && scs3-win.exe upload .\runtime\build\src\Release\csharp-module.dll coreclr-module/x64_win32/csharp-module.dll
    on:
      repo: FabianTerhorst/coreclr-module
      condition: "$TRAVIS_OS_NAME = windows"
      tags: true
      branches:
        only:
        - master
  - provider: script
    skip_cleanup: true
    script: cd .. && cd .. && cd .. && chmod +x ./scs3-linux && ./scs3-linux upload ./runtime/build/src/libcsharp-module.so coreclr-module/x64_linux/libcsharp-module.so
    on:
      repo: FabianTerhorst/coreclr-module
      condition: "$TRAVIS_OS_NAME = linux"
      tags: true
      branches:
        only:
        - master
