name: C/C++ CI

on:
  push:
    paths:
    - 'runtime/**'
    - '.github/workflows/runtime.yml'

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      working-directory: ./runtime
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
    - name: build
      run: cd build && cmake --build build --config Release

  build-windows:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      working-directory: ./runtime
      run: mkdir build && cd build && cmake -G"Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=RelWithDebInfo -T host=x64 ..
    - name: build
      run: cmake --build build --config Release
